M48
; DRILL file {KiCad 8.0.6} date 2024-12-30T15:48:23-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-12-30T15:48:23-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.600
%
G90
G05
T1
X101.264Y-77.14
X105.351Y-81.227
T2
X102.709Y-96.438
X108.709Y-96.438
T3
X35.052Y-82.928
X39.294Y-78.685
M30
